### ISSUE TITLE
Can not start plantgateway docker, can't initialize device: invalid argument

### ISSUE THREAD

**Issue by JBS5** [pschmitt/docker-plantgateway#4]
After downloading the docker image https://hub.docker.com/r/pschmitt/plantgateway/, edited the .plantgw.yaml in the home folder of the RPi3, the docker image can not start:

```
pi@raspberrypi:~ $ sudo docker run pschmitt/plantgateway
Initializing hci0
Can't open serial port: No such file or directory
Can't initialize device: Invalid argument
Retrying initialization
Can't open serial port: No such file or directory
Can't initialize device: Invalid argument
```

Because the bluetooth interface seems to be on hci0, I did not change that part in the .plantgw.yaml.

Here is a prinscreen where I scan for bluetooth devices, list the bluetooth interfaces and then start the docker: https://i.imgur.com/US433nV.png

Can you point me in the right direction?

**Comment by JBS5** [comment]
Using --net=host to start the image gives me another 2 errors.

```
pi@raspberrypi:/home $ sudo docker run --net=host pschmitt/plantgateway
Traceback (most recent call last):
  File "/usr/local/bin/plantgateway", line 27, in <module>
    main()
  File "/usr/local/bin/plantgateway", line 14, in main
    pg = PlantGateway()
  File "/usr/local/lib/python3.6/site-packages/plantgw/plantgw.py", line 128, in __init__
    self.config = Configuration(config_file_path)
  File "/usr/local/lib/python3.6/site-packages/plantgw/plantgw.py", line 32, in __init__
    with open(config_file_path, 'r') as config_file:
FileNotFoundError: [Errno 2] No such file or directory: '/root/.plantgw.yaml'
```

The first one, I don't get whats going on or what to do with it.
The second one is about missing the .plantgw.yaml in /root/ but I thought that file needs to be in the home dir?

`# copy this file to your home directory and rename it to ".plantgw.yaml" (starting with a ".").`

**Comment by JBS5** [comment]
Fixed by mapping the local plantgw.yaml while starting the docker image.
